# Control your input devices
# See https://wiki.hypr.land/Configuring/Variables/#input
input {
  # Use multiple keyboard layouts and switch between them with Left Alt + Right Alt
  # kb_layout = us,dk,eu
  kb_layout = fr
  kb_options = grp:shift_caps_toggle

  # Change speed of keyboard repeat
  repeat_rate = 40
  repeat_delay = 600

  # Start with numlock on by default
  numlock_by_default = true

  # Increase sensitivity for mouse/trackpad (default: 0)
  sensitivity = 0 # Default for all devices

  touchpad {
    # Use natural (inverse) scrolling
     natural_scroll = true

    # Use two-finger clicks for right-click instead of lower-right corner
    # clickfinger_behavior = true

    # Control the speed of your scrolling
    scroll_factor = 0.4
  }
}

# Customize settings for specific devices
# Use `hyprctl devices` to get the exact device name
device[hp-2.4g-wireless-and-bt-mouse] {
  sensitivity = -1
}


# Enable touchpad gestures for changing workspaces
# See https://wiki.hyprland.org/Configuring/Gestures/
 gesture = 3, horizontal, workspace
